language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - travis_retry python setup.py develop easy_install pyAudioGraph[testing]
# command to run tests
script: py.tests --runslow